### ISSUE TITLE
Unknown dependencies 

### ISSUE THREAD

**Issue by ghost** [joeleoli/zoot#1]
Zoot requires multiple different dependencies after imported.  Could you release a zip folder of all the dependencies?

**Comment by Cyclize** [comment]
Or maybe update the pom.xml to make sure all dependencies are installed properly

**Comment by niikoolaa04** [comment]
Yeah, please

**Comment by vznxyz** [comment]
#https://github.com/joeleoli/zoot/commit/8e63d4f94430564fae09edf8a3e147c5283734a9 should fix this

**Comment by Cyclize** [comment]
I think you can close the issue now :)
